const detailsHotels = [
  {
    id: 1,
    name: "Hotel Luxo",
    description: "Um hotel luxuoso com tudo o que você precisa.",
    images: [
      "https://plus.unsplash.com/premium_photo-1661962739798-0af59dc30d14?q=80&w=1129&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://plus.unsplash.com/premium_photo-1661963239507-7bdf41a5e66b?q=80&w=1046&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://plus.unsplash.com/premium_photo-1661884238187-1c274b3c3413?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://plus.unsplash.com/premium_photo-1661876306620-f2f2989f8f8b?q=80&w=1084&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    rating: 5,
    city: "São Paulo",
    state: "SP",
    price: 350,
    address: "Avenida Luxo, 1234 - Centro, São Paulo - SP",
    landmark: "500m até a Avenida Paulista",
    promotion: "10% de desconto para estadias acima de 3 dias!",
    actionCall: "Fique hospedado no hotel mais charmoso da região!",
    localDescription:
      "Localizado no coração de São Paulo, perto das melhores atrações.",
    services: [
      "Wi-Fi gratuito",
      "Café da manhã incluído",
      "Serviço de quarto 24h",
    ],
  },
  {
    id: 2,
    name: "Hotel Econômico",
    description: "A opção perfeita para quem busca conforto e economia.",
    images: [
      "https://via.placeholder.com/400x300?text=Hotel+Econ+1",
      "https://via.placeholder.com/400x300?text=Hotel+Econ+2",
      "https://via.placeholder.com/400x300?text=Hotel+Econ+3",
      "https://via.placeholder.com/400x300?text=Hotel+Econ+4",
    ],
    rating: 3,
    city: "Rio de Janeiro",
    state: "RJ",
    price: 150,
    address: "Rua da Economia, 456 - Copacabana, Rio de Janeiro - RJ",
    landmark: "2min a pé da praia de Copacabana",
    promotion: "Café da manhã grátis para reservas diretas!",
    actionCall: "Experimente o melhor do Rio sem gastar muito!",
    localDescription: "Próximo aos melhores pontos turísticos da zona sul.",
    services: ["Café da manhã incluído", "Transporte para o aeroporto"],
  },
  {
    id: 3,
    name: "Hotel Premium",
    description: "Acomodações de alto padrão para hóspedes exigentes.",
    images: [
      "https://via.placeholder.com/400x300?text=Hotel+Premium+1",
      "https://via.placeholder.com/400x300?text=Hotel+Premium+2",
      "https://via.placeholder.com/400x300?text=Hotel+Premium+3",
      "https://via.placeholder.com/400x300?text=Hotel+Premium+4",
    ],
    rating: 4,
    city: "Belo Horizonte",
    state: "MG",
    price: 250,
    address: "Rua do Premium, 789 - Savassi, Belo Horizonte - MG",
    landmark: "300m até a Praça da Liberdade",
    actionCall: "Viva uma experiência única e sofisticada!",
    localDescription: "Situado em uma das áreas mais nobres da cidade.",
    services: ["Spa", "Academia", "Restaurante gourmet"],
  },
  {
    id: 4,
    name: "Resort Maravilha",
    description: "O paraíso à beira-mar, perfeito para relaxar.",
    images: [
      "https://via.placeholder.com/400x300?text=Resort+1",
      "https://via.placeholder.com/400x300?text=Resort+2",
      "https://via.placeholder.com/400x300?text=Resort+3",
      "https://via.placeholder.com/400x300?text=Resort+4",
    ],
    rating: 5,
    city: "Fortaleza",
    state: "CE",
    price: 600,
    address: "Avenida da Praia, 100 - Praia do Futuro, Fortaleza - CE",
    landmark: "1min a pé da praia",
    actionCall: "Desfrute do sol e do mar em um resort de luxo!",
    localDescription: "Ideal para quem busca relaxamento e diversão.",
    services: ["Praia privativa", "Atividades aquáticas", "Serviço de praia"],
  },
  {
    id: 5,
    name: "Pousada Tranquila",
    description: "Um refúgio de paz e natureza.",
    images: [
      "https://via.placeholder.com/400x300?text=Pousada+1",
      "https://via.placeholder.com/400x300?text=Pousada+2",
      "https://via.placeholder.com/400x300?text=Pousada+3",
      "https://via.placeholder.com/400x300?text=Pousada+4",
    ],
    rating: 4,
    city: "Gramado",
    state: "RS",
    price: 200,
    address: "Rua da Tranquilidade, 45 - Centro, Gramado - RS",
    landmark: "800m até o Lago Negro",
    promotion: "Desconto especial para casais!",
    actionCall: "Relaxar nunca foi tão fácil!",
    localDescription: "Rodeado por montanhas e natureza exuberante.",
    services: ["Café da manhã", "Jardim", "Atividades ao ar livre"],
  },
  {
    id: 6,
    name: "Hotel Econômico Praia",
    description: "Conforto a um preço acessível perto da praia.",
    images: [
      "https://via.placeholder.com/400x300?text=Hotel+Econ+Praia+1",
      "https://via.placeholder.com/400x300?text=Hotel+Econ+Praia+2",
      "https://via.placeholder.com/400x300?text=Hotel+Econ+Praia+3",
      "https://via.placeholder.com/400x300?text=Hotel+Econ+Praia+4",
    ],
    rating: 3,
    city: "Salvador",
    state: "BA",
    price: 120,
    address: "Rua da Praia, 89 - Barra, Salvador - BA",
    landmark: "5min a pé da praia",
    actionCall: "Aproveite o melhor da praia sem gastar muito!",
    localDescription: "Perfeito para quem quer diversão e conforto.",
    services: ["Wi-Fi", "Transporte para a praia"],
  },
  {
    id: 7,
    name: "Hostel Estilo",
    description: "Um hostel moderno e acolhedor.",
    images: [
      "https://via.placeholder.com/400x300?text=Hostel+Estilo+1",
      "https://via.placeholder.com/400x300?text=Hostel+Estilo+2",
      "https://via.placeholder.com/400x300?text=Hostel+Estilo+3",
      "https://via.placeholder.com/400x300?text=Hostel+Estilo+4",
    ],
    rating: 4,
    city: "Curitiba",
    state: "PR",
    price: 230,
    address: "Rua do Estilo, 33 - Centro, Curitiba - PR",
    landmark: "300m até a Praça Tiradentes",
    actionCall: "Experimente o melhor do estilo de vida jovem!",
    localDescription: "Próximo a bares e restaurantes badalados.",
    services: ["Cozinha compartilhada", "Sala de estar"],
  },
  {
    id: 8,
    name: "Hotel Vista Mar",
    description: "Vista incrível do mar e excelente serviço.",
    images: [
      "https://via.placeholder.com/400x300?text=Hotel+Vista+Mar+1",
      "https://via.placeholder.com/400x300?text=Hotel+Vista+Mar+2",
      "https://via.placeholder.com/400x300?text=Hotel+Vista+Mar+3",
      "https://via.placeholder.com/400x300?text=Hotel+Vista+Mar+4",
    ],
    rating: 5,
    city: "Natal",
    state: "RN",
    price: 500,
    address: "Avenida do Mar, 12 - Ponta Negra, Natal - RN",
    landmark: "1min a pé da praia",
    actionCall: "Desfrute da melhor vista do mar!",
    localDescription: "Localizado em uma das praias mais famosas do Brasil.",
    services: ["Praia", "Restaurante à beira-mar"],
  },
  {
    id: 9,
    name: "Pousada da Montanha",
    description: "Conforto nas montanhas.",
    images: [
      "https://via.placeholder.com/400x300?text=Pousada+Montanha+1",
      "https://via.placeholder.com/400x300?text=Pousada+Montanha+2",
      "https://via.placeholder.com/400x300?text=Pousada+Montanha+3",
      "https://via.placeholder.com/400x300?text=Pousada+Montanha+4",
    ],
    rating: 3,
    city: "Campos do Jordão",
    state: "SP",
    price: 180,
    address: "Estrada da Montanha, 100 - Vila Capivari, Campos do Jordão - SP",
    landmark: "400m até o centro de Capivari",
    actionCall: "Viva momentos de tranquilidade nas montanhas!",
    localDescription: "A pousada oferece uma vista espetacular das montanhas.",
    services: ["Café da manhã", "Trilhas", "Atividades ao ar livre"],
  },
  {
    id: 10,
    name: "Hostel Charmoso",
    description: "Um hostel aconchegante e acolhedor.",
    images: [
      "https://via.placeholder.com/400x300?text=Hostel+Charmoso+1",
      "https://via.placeholder.com/400x300?text=Hostel+Charmoso+2",
      "https://via.placeholder.com/400x300?text=Hostel+Charmoso+3",
      "https://via.placeholder.com/400x300?text=Hostel+Charmoso+4",
    ],
    rating: 4,
    city: "Olinda",
    state: "PE",
    price: 270,
    address: "Rua do Charmoso, 15 - Centro, Olinda - PE",
    landmark: "5min a pé do Alto da Sé",
    actionCall: "Descubra a cultura e a beleza de Olinda!",
    localDescription: "Próximo a pontos turísticos históricos e culturais.",
    services: ["Cozinha compartilhada", "Eventos sociais"],
  },
  {
    id: 11,
    name: "Hotel Centro",
    description: "Ideal para quem quer explorar a cidade.",
    images: [
      "https://via.placeholder.com/400x300?text=Hotel+Centro+1",
      "https://via.placeholder.com/400x300?text=Hotel+Centro+2",
      "https://via.placeholder.com/400x300?text=Hotel+Centro+3",
      "https://via.placeholder.com/400x300?text=Hotel+Centro+4",
    ],
    rating: 2,
    city: "São Paulo",
    state: "SP",
    price: 100,
    address: "Rua da Exploração, 1 - Centro, São Paulo - SP",
    landmark: "300m até a Praça da Sé",
    actionCall: "Perfeito para quem deseja conhecer São Paulo!",
    localDescription:
      "Localizado no coração da cidade, próximo a várias atrações.",
    services: ["Wi-Fi", "Transporte público próximo"],
  },
  {
    id: 12,
    name: "Resort do Sol",
    description: "Resort com diversas atividades para toda a família.",
    images: [
      "https://via.placeholder.com/400x300?text=Resort+Sol+1",
      "https://via.placeholder.com/400x300?text=Resort+Sol+2",
      "https://via.placeholder.com/400x300?text=Resort+Sol+3",
      "https://via.placeholder.com/400x300?text=Resort+Sol+4",
    ],
    rating: 5,
    city: "Rio de Janeiro",
    state: "RJ",
    price: 700,
    address: "Avenida do Sol, 1 - Barra da Tijuca, Rio de Janeiro - RJ",
    landmark: "1min a pé da praia",
    actionCall: "Desfrute de momentos inesquecíveis à beira-mar!",
    localDescription: "Ideal para relaxar e aproveitar a praia com a família.",
    services: ["Praia", "Atividades recreativas", "Restaurante"],
  },
  {
    id: 13,
    name: "Hotel da Praia",
    description: "Ótima localização na praia com conforto.",
    images: [
      "https://via.placeholder.com/400x300?text=Hotel+Praia+1",
      "https://via.placeholder.com/400x300?text=Hotel+Praia+2",
      "https://via.placeholder.com/400x300?text=Hotel+Praia+3",
      "https://via.placeholder.com/400x300?text=Hotel+Praia+4",
    ],
    rating: 4,
    city: "Florianópolis",
    state: "SC",
    price: 350,
    address: "Rua da Praia, 123 - Lagoa da Conceição, Florianópolis - SC",
    landmark: "200m até a Lagoa",
    actionCall: "Aproveite a beleza natural de Florianópolis!",
    localDescription: "Próximo a restaurantes e atividades aquáticas.",
    services: ["Wi-Fi gratuito", "Transporte para a praia"],
  },
  {
    id: 14,
    name: "Pousada Aconchego",
    description: "Um lugar acolhedor para relaxar.",
    images: [
      "https://via.placeholder.com/400x300?text=Pousada+Aconchego+1",
      "https://via.placeholder.com/400x300?text=Pousada+Aconchego+2",
      "https://via.placeholder.com/400x300?text=Pousada+Aconchego+3",
      "https://via.placeholder.com/400x300?text=Pousada+Aconchego+4",
    ],
    rating: 3,
    city: "São Miguel dos Milagres",
    state: "AL",
    price: 150,
    address: "Rua do Aconchego, 456 - Centro, São Miguel dos Milagres - AL",
    landmark: "500m até a Praia do Patacho",
    actionCall: "Descanse e relaxe em um ambiente acolhedor!",
    localDescription: "Rodeada por belezas naturais e tranquilidade.",
    services: ["Café da manhã", "Atividades ao ar livre"],
  },
  {
    id: 15,
    name: "Hostel Cosmos",
    description: "Hostel confortável e acessível.",
    images: [
      "https://via.placeholder.com/400x300?text=Hostel+Cosmos+1",
      "https://via.placeholder.com/400x300?text=Hostel+Cosmos+2",
      "https://via.placeholder.com/400x300?text=Hostel+Cosmos+3",
      "https://via.placeholder.com/400x300?text=Hostel+Cosmos+4",
    ],
    rating: 5,
    city: "Belo Horizonte",
    state: "MG",
    price: 400,
    address: "Rua do Cosmos, 100 - Centro, Belo Horizonte - MG",
    landmark: "200m até a Praça da Liberdade",
    actionCall: "Venha se hospedar em um ambiente jovem e divertido!",
    localDescription: "Próximo a bares e restaurantes badalados.",
    services: ["Cozinha compartilhada", "Eventos sociais"],
  },
  {
    id: 16,
    name: "Resort Verde",
    description: "Um resort ideal para famílias.",
    images: [
      "https://via.placeholder.com/400x300?text=Resort+Verde+1",
      "https://via.placeholder.com/400x300?text=Resort+Verde+2",
      "https://via.placeholder.com/400x300?text=Resort+Verde+3",
      "https://via.placeholder.com/400x300?text=Resort+Verde+4",
    ],
    rating: 4,
    city: "Ilhéus",
    state: "BA",
    price: 350,
    address: "Avenida Verde, 22 - Praia do Norte, Ilhéus - BA",
    landmark: "5min a pé da praia",
    actionCall: "Aproveite momentos de lazer com sua família!",
    localDescription: "Localizado em uma área tranquila, ideal para férias.",
    services: ["Piscina", "Restaurante", "Praia"],
  },
  {
    id: 17,
    name: "Hotel Middle Age",
    description: "Hotel com temática medieval.",
    images: [
      "https://via.placeholder.com/400x300?text=Hotel+Middle+Age+1",
      "https://via.placeholder.com/400x300?text=Hotel+Middle+Age+2",
      "https://via.placeholder.com/400x300?text=Hotel+Middle+Age+3",
      "https://via.placeholder.com/400x300?text=Hotel+Middle+Age+4",
    ],
    rating: 3,
    city: "Petrópolis",
    state: "RJ",
    price: 170,
    address: "Rua Medieval, 10 - Centro, Petrópolis - RJ",
    landmark: "300m até o Museu Imperial",
    actionCall: "Viva uma experiência única em um ambiente medieval!",
    localDescription: "Próximo a castelos e pontos turísticos históricos.",
    services: ["Eventos temáticos", "Restaurante medieval"],
  },
  {
    id: 18,
    name: "Premier Inn",
    description: "Conforto e qualidade em um só lugar.",
    images: [
      "https://via.placeholder.com/400x300?text=Premier+Inn+1",
      "https://via.placeholder.com/400x300?text=Premier+Inn+2",
      "https://via.placeholder.com/400x300?text=Premier+Inn+3",
      "https://via.placeholder.com/400x300?text=Premier+Inn+4",
    ],
    rating: 5,
    city: "São Paulo",
    state: "SP",
    price: 600,
    address: "Avenida da Qualidade, 200 - Jardins, São Paulo - SP",
    landmark: "400m até a Rua Oscar Freire",
    actionCall: "Hospede-se com conforto e qualidade no coração de São Paulo!",
    localDescription: "Próximo a boutiques e restaurantes renomados.",
    services: ["Academia", "Café da manhã", "Wi-Fi gratuito"],
  },
];

if (!localStorage.getItem("details")) {
  localStorage.setItem("details", JSON.stringify(detailsHotels));
}

export default detailsHotels;
